version: 2

python:
  version: "3"
  install:
    - requirements: etc/doc/requirements.txt
  system_packages: true

sphinx:
  builder: dirhtml
  configuration: source/conf.py
  fail_on_warning: false
